routes/admin.php
<?php

use App\Http\Controllers\{CategoriesController,CourseController,SeriesController,VideoController};
use Illuminate\Support\Facades\Route;
use App\Models\Category;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::get('/dashboard', function () {
    return view('layouts.dashboard');
})->middleware(['auth', 'verified'])->name('admin.dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('categories', CategoriesController::class)->names('admin.categories');
    Route::resource('courses', CourseController::class)->names('admin.courses');
    Route::resource('series', SeriesController::class)->names('admin.series');
    Route::resource('videos', VideoController::class)->names('admin.videos');
});

routes/web.php
<?php

use App\Http\Controllers\{ProfileController};
use App\Http\Controllers\Users\{CategoryController};
use Illuminate\Support\Facades\Route;
use App\Models\Category;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    $categories =  Category::whereNull('parent_id')->get();
    return view('welcome', compact('categories'));
});

Route::get('/dashboard', function () {
    return view('users.layouts.dashboard');
})->name('dashboard');

Route::middleware('auth')->group(function () {


    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('categories', CategoryController::class)->names('categories');

    
});


require __DIR__.'/auth.php';

resources/views/layouts/courses/actions.blade.php
<!-- <a  onclick='ActiveCourse({{ $course->id }})' type="button" class="btn btn-primary"><i class="fa fa-check" aria-hidden="true"></i></a> -->
<a onclick='DisableCourse({{ $course->id }})' type="button" class="btn btn-warning"><i class="fa-regular fa-circle-xmark" aria-hidden="true"></i></a>
<a href="{{route('admin.courses.edit', $course->id)}}" type="button" class="btn btn-success"><i class="fa fa-edit" aria-hidden="true"></i></a>
<!-- <a onclick='DeleteCourse({{ $course->id }})' type="button" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a> -->

resources/views/layouts/courses/add.blade.php
@extends('master')

@section('title')
    {{isset($course)?'Update ':'Add ' }}Course
@stop
@section('header')
    {{isset($course)?'Update':'Add' }} Course
@stop
@push('end-style')
    <link href="{{ asset('assets/assets/css/scrollspyNav.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/plugins/file-upload/file-upload-with-preview.min.css') }}" rel="stylesheet" type="text/css" />
@endpush
@push('end-script')
    <script src="{{ asset('assets/assets/js/scrollspyNav.js') }}"></script>
    <script src="{{ asset('assets/plugins/file-upload/file-upload-with-preview.min.js') }}"></script>

    <script>
        //First upload
        var firstUpload = new FileUploadWithPreview('myFirstImage')
        //Second upload
        var secondUpload = new FileUploadWithPreview('mySecondImage')
    </script>
    <script>
        $(document).ready(function() {
            //set initial state.
            $('#is_popular').prop('checked', false);
            $('#is_parent').prop('checked', false);

           var course = @json($course ?? null);

            if (typeof course !== 'undefined' && course.icon) {
                // generate the base URL dynamically
                var baseUrl = '{{ url("/") }}';
                var fullIconUrl = baseUrl + '/' + course.icon;
                // Change the background image to the full icon URL
                $('.custom-file-container__image-preview').css('background', 'url(' + fullIconUrl + ')');
                $('.custom-file-container__image-preview').css('background-repeat', 'no-repeat');
                $('.custom-file-container__image-preview').css('background-size', 'contain');
                $('.custom-file-container__image-preview').css('background-position', 'center');
            }
        });

    </script>
@endpush

@section('content')

    <div id="content" class="main-content">
        <div class="layout-px-spacing">

            <div class="row layout-top-spacing">

                <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                    <div class="widget-content widget-content-area br-6">


                        <form action="{{ isset($course) ? route('admin.courses.update', $course->id) : route('admin.courses.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf

                            @if(isset($course))
                                @method("PUT")
                            @endif

                            <div class="form-group">
                                <label for="exampleInputEmail1">Title</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter title" name="title" value="{{ old('title', isset($course) ? $course->title : '') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Parent course</label>
                                <select class="form-control basic" name="category_id">
                                    <option disabled selected value> -- Select Parent if any -- </option>
                                    @foreach ($categories as $option)
                                        <option value="{{ $option->id }}" {{ old('category_id', isset($course) ? ($course->category_id == $option->id ? 'selected' : '') : '') }}>{{ $option->title }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="custom-file-container" data-upload-id="myFirstImage">
                                <label>Upload (Single File) <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
                                <label class="custom-file-container__custom-file">
                                    <input name="icon" type="file" class="custom-file-container__custom-file__custom-file-input" accept="image/*" required>
                                    <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
                                    <span class="custom-file-container__custom-file__custom-file-control"></span>
                                </label>
                                <div class="custom-file-container__image-preview"></div>
                            </div>

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>

                    </div>
                </div>

            </div>

        </div>

    </div>


@stop

resources/views/layouts/courses/icon.blade.php
<img src="{{ asset($course->icon) }}" height="50px" width="50px">

resources/views/layouts/courses/index.blade.php
@extends('master')
@push('end-style')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/table/datatable/datatables.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/table/datatable/custom_dt_html5.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/table/datatable/dt-global_style.css') }}">
@endpush
@push('end-script')
    <script src="{{ asset('assets/plugins/table/datatable/datatables.js') }}"></script>
    <!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/buttons.print.min.js') }}"></script>
    <script>
        $('#courses_table').DataTable({
            "dom": "<'dt--top-section'<'row'<'col-sm-12 col-md-6 d-flex justify-content-md-start justify-content-center'B><'col-sm-12 col-md-6 d-flex justify-content-md-end justify-content-center mt-md-0 mt-3'f>>>" +
                "<'table-responsive'tr>" +
                "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
            buttons: {
                buttons: [{
                        extend: 'copy',
                        className: 'btn btn-sm'
                    },
                    {
                        extend: 'csv',
                        className: 'btn btn-sm'
                    },
                    {
                        extend: 'excel',
                        className: 'btn btn-sm'
                    },
                    {
                        extend: 'print',
                        className: 'btn btn-sm'
                    }
                ]
            },
            ajax: "{{ route('admin.courses.index') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'slug',
                    name: 'slug'
                },
                {
                    data: 'icon',
                    name: 'icon'
                },
                {
                    data: 'actions',
                    name: 'actions'
                }
            ],
            "oLanguage": {
                "oPaginate": {
                    "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>',
                    "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'
                },
                "sInfo": "Showing page _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Search...",
                "sLengthMenu": "Results :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [7, 10, 20, 50],
            "pageLength": 7
        });
    </script>
@endpush

@section('title')
    Courses
@stop
@section('header')
    Course List
@stop

@section('content')
    
    
    <div id="content" class="main-content">
        <div class="layout-px-spacing">

            <div class="row layout-top-spacing">
                <!-- @if(session('success'))
                    <div class="alert alert-success alert-dismissible float-right fade show position-fixed m-3" role="alert">
                        {{ session('success') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif -->
                <div class="col-12">
                    <a type="button" href="{{route('admin.courses.create')}}" class="btn btn-dark float-right ms-auto mb-2">Add
                        Course</a>
                </div>
                

                <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                    <div class="widget-content widget-content-area br-6">

                        <table id="courses_table" class="table table-hover non-hover" style="width:100%">

                            <thead>

                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>Slug</th>
                                    <th>Icon</th>
                                    <th class="dt-no-sorting">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>


    <script>
        function DisableCategory(id) {
            swal.fire({
                title: "Are you sure to disable this category?",
                text: "User will not be able to see any products under this category",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, disable it!",
            }).then((result) => {
                //  console.log(isConfirm);
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: '{{ url('category_disable') }}/' + id,

                        success: function(data) {
                            $('#courses_table').DataTable().ajax.reload();
                            swal.fire("Success", " Category disabled successfully", "success");
                        },
                        error: function(error) {
                            Snackbar.show({
                                text: 'Somthing Went Wrong',
                                pos: 'top-right',
                                actionTextColor: '#fff',
                                backgroundColor: '#e7515a'
                            });
                        }
                    });
                }
            });

        }

        function ActiveCategory(id) {
            swal.fire({
                title: "Are you sure to Active this category?",
                text: "It will be visible to users",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Activate it!",
            }).then((result) => {
                //  console.log(isConfirm);
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: '{{ url('category_active') }}/' + id,

                        success: function(data) {
                            $('#courses_table').DataTable().ajax.reload();
                            swal.fire("Success", " Category Activated successfully", "success");
                        },
                        error: function(error) {
                            Snackbar.show({
                                text: 'Somthing Went Wrong',
                                pos: 'top-right',
                                actionTextColor: '#fff',
                                backgroundColor: '#e7515a'
                            });
                        }
                    });
                }
            });

        }

        function DeleteCategory(id) {
            swal.fire({
                title: "Are you sure to delete this category?",
                text: "All products under this category will automatically delete",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
            }).then((result) => {
                //  console.log(isConfirm);
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: '{{ url('category_delete') }}/' + id,

                        success: function(data) {
                            $('#courses_table').DataTable().ajax.reload();
                            swal.fire("Success", "Category deleted successfully", "success");
                        },
                        error: function(error) {
                            Snackbar.show({
                                text: 'Somthing Went Wrong',
                                pos: 'top-right',
                                actionTextColor: '#fff',
                                backgroundColor: '#e7515a'
                            });
                        }
                    });
                }
            });

        }
    </script>
@stop