routes/admin.php
<?php

use App\Http\Controllers\{CategoriesController,CourseController,SeriesController,VideoController};
use Illuminate\Support\Facades\Route;
use App\Models\Category;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::get('/dashboard', function () {
    return view('layouts.dashboard');
})->middleware(['auth', 'verified'])->name('admin.dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('categories', CategoriesController::class)->names('admin.categories');
    Route::resource('courses', CourseController::class)->names('admin.courses');
    Route::resource('series', SeriesController::class)->names('admin.series');
    Route::resource('videos', VideoController::class)->names('admin.videos');
});

routes/web.php
<?php

use App\Http\Controllers\{ProfileController};
use App\Http\Controllers\Users\{CategoryController};
use Illuminate\Support\Facades\Route;
use App\Models\Category;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    $categories =  Category::whereNull('parent_id')->get();
    return view('welcome', compact('categories'));
});

Route::get('/dashboard', function () {
    return view('users.layouts.dashboard');
})->name('dashboard');

Route::middleware('auth')->group(function () {


    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('categories', CategoryController::class)->names('categories');

    
});


require __DIR__.'/auth.php';

app/Models/Video.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    
    use Sluggable;
    use HasFactory;
    protected $guarded = [];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }


    public function series()
    {
        return $this->belongsTo(Series::class);
    }

    public function topics()
    {
        return $this->hasMany(Topic::class);
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use App\Models\Video;
use App\Models\Series;
use Illuminate\Support\Facades\Storage;

class VideoController extends Controller
{

    private function make_directory_path($category)
    {
        $path = str_replace(' ', '_', trim($category->title)); // Trim leading and trailing spaces and replace spaces with underscores

        if ($category->parent) {
            $parentPath = $this->make_directory_path($category->parent);
            $path = $parentPath . '/' . $path;
        }

        return trim($path, '/');
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (request()->ajax()) {
            $videos = Video::with('series')->get();

            return DataTables::of($videos)
                ->addIndexColumn()
                ->editColumn('title', function ($video) {
                    return ucfirst($video->title);
                })
                // Add other columns as needed
                ->editColumn('category', function ($video) {
                    return ($video->series_id) ? ucfirst($video->series->title) : 'N/A';
                })
                ->editColumn('video', function ($video) {
                    return "<a href='".$video->video_url."'>video</a>";
                })
                ->editColumn('actions', function ($video) {
                    return view('layouts.videos.actions', compact('video'));
                })
                ->rawColumns(['actions','video'])
                ->toJson();
        }

        return view('layouts.videos.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $series = Series::orderBy('title', 'ASC')->get();
        return view('layouts.videos.add', compact('series'));
    }

    /**
     * Store a newly created resource in storage.
     */
    // public function store(Request $request)
    // {
    //     $request->validate([
    //         'series_id' => 'required|exists:categories,id',
    //         'title' => 'required|string',
    //         'description' => 'required|string',
    //         'video_file' => 'required|mimetypes:video/*',
    //     ]);
    
    //     $category = Category::find($request->series_id);
    
    //     $dir_path = $this->make_directory_path($category);
    
    //     $file = $request->file('video_file');
    //     $fileName = $file->hashName(); // Use a hashed name for the file
    //     $filePath = $dir_path . '/' . $fileName; // Append the file name to the directory path
    
    //     // Store the video file in S3 with the modified file path
    //     Storage::disk('s3')->put($filePath, $request->file('video_file'));
    
    //     $videoUrl = Storage::disk('s3')->url($filePath);
    
    //     Video::create([
    //         'series_id' => $request->input('series_id'),
    //         'title' => $request->input('title'),
    //         'description' => $request->input('description'),
    //         'video_url' => $videoUrl,
    //         // Add other fields as needed
    //     ]);
    
    //     return redirect()->route('admin.videos.index')->with('success', 'Video created successfully!');
    // }

    // public function store(Request $request)
    // {
    //     $request->validate([
    //         'series_id' => 'required|exists:categories,id',
    //         'title' => 'required|string',
    //         'description' => 'required|string',
    //         'video_file' => 'required|mimetypes:video/*', // Assuming 'video_file' is the name attribute of your file input
    //         // Add other validation rules as needed
    //     ]);
    //     // dump(env('AWS_ACCESS_KEY_ID'));
    //     // dump(env('AWS_SECRET_ACCESS_KEY'));
    //     // dump(env('AWS_DEFAULT_REGION'));
    //     // dump(env('AWS_BUCKET'));
    //     // dump(env('AWS_USE_PATH_STYLE_ENDPOINT'));
        
    //     $category = Category::find($request->series_id);


    //     $dir_path = $this->make_directory_path($category);

    //     $file = $request->file('video_file');
    //     $fileName = $file->hashName();
    //     try {
    //         $filePath = Storage::disk('s3')->put('/', $request->file('video_file'));

    //         $videoUrl = Storage::disk('s3')->url($filePath);
    
    //         Video::create([
    //             'series_id' => $request->input('series_id'),
    //             'title' => $request->input('title'),
    //             'description' => $request->input('description'),
    //             'video_url' => $videoUrl,
    //             // Add other fields as needed
    //         ]);
    //     }catch(\Exception $e){
    //         return $e->getMessage();
    //     }
       

    //     return redirect()->route('admin.videos.index')->with('success', 'Video created successfully!');
    // }
    public function store(Request $request)
    {
        $request->validate([
            'series_id' => 'required|exists:categories,id',
            'title' => 'required|string',
            'description' => 'required|string',
            'video_file' => 'required|mimetypes:video/*',
        ]);

        $category = Series::find($request->series_id);

        $dir_path = $this->make_directory_path($category);
        //local storage code
        // $file      = $request->file('video_file');
        // $file_path = Storage::put('public/'.$dir_path, $file);
        // $file_path = str_replace("public","storage",$file_path);
        // $videoUrl = $file_path;

        //S3 storage code
        $file = $request->file('video_file');
        $fileName = $file->hashName();
        $filePath = $dir_path.'/'.$fileName;
                
        Storage::disk('s3')->put($filePath, file_get_contents($file));
        // Storage::disk('s3')->assertExists($filePath,300);
        $videoUrl = Storage::disk('s3')->url($filePath);

        Video::create([
            'series_id' => $request->input('series_id'),
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'video_url' => $videoUrl,
            // Add other fields as needed
        ]);
        // } catch (\Exception $e) {
        //     return $e->getMessage();
        // }

        return redirect()->route('admin.videos.index')->with('success', 'Video created successfully!');
    }


    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $video = Video::find($id);

        return view('layouts.videos.show', compact('video'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        
        $video = Video::find($id);
        $series = Series::orderBy('title', 'ASC')->get();

        return view('layouts.videos.add', compact('series', 'video'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'series_id' => 'sometimes|exists:categories,id',
            'title' => 'sometimes|string',
            'description' => 'sometimes|string',
            'video_file' => 'sometimes|mimetypes:video/*',
            // Add other validation rules as needed
        ]);
    
        $video = Video::find($id);
    
        if ($request->hasFile('video_file')) {
            $file = $request->file('video_file');
            $fileName = $file->hashName();
            $filePath = $dir_path . '/' . $fileName;
    
            // Delete old video file if it exists
            if (Storage::disk('s3')->exists($video->video_url)) {
                Storage::disk('s3')->delete($video->video_url);
            }
    
            Storage::disk('s3')->put($filePath, file_get_contents($file));
            $request['video_url'] = Storage::disk('s3')->url($filePath);
        }
    
        $video->update($request->except('video_file', '_token'));
    
        return redirect()->route('admin.videos.index')->with('success', 'Video updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $video = Video::find($id);
        $video->delete();

        return redirect()->route('admin.videos.index')->with('success', 'Video deleted successfully!');
    }


}

resources/views/layouts/videos/actions.blade.php
<a href="{{route('admin.videos.edit', $video->id)}}" type="button" class="btn btn-success"><i class="fa fa-edit" aria-hidden="true"></i></a>
<a onclick='DeleteCategory({{ $video->id }})' type="button" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>

resources/views/layouts/videos/add.blade.php
@extends('master')

@section('title')
    {{isset($video)?'Update ':'Add ' }}video
@stop
@section('header')
    {{isset($video)?'Update':'Add' }} video
@stop
@push('end-style')
    <link href="{{ asset('assets/assets/css/scrollspyNav.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/plugins/file-upload/file-upload-with-preview.min.css') }}" rel="stylesheet" type="text/css" />
@endpush
@push('end-script')
    <script src="{{ asset('assets/assets/js/scrollspyNav.js') }}"></script>
    <script src="{{ asset('assets/plugins/file-upload/file-upload-with-preview.min.js') }}"></script>

    <script>
        //First upload
        var firstUpload = new FileUploadWithPreview('myFirstImage')
        //Second upload
        var secondUpload = new FileUploadWithPreview('mySecondImage')
    </script>
    <script>
        $(document).ready(function() {
            //set initial state.
            $('#is_popular').prop('checked', false);
            $('#is_parent').prop('checked', false);

           var video = @json($video ?? null);
           console.log(video);

             if (typeof video !== 'undefined' && video.video_url) {
                 // generate the base URL dynamically
                 var baseUrl = '{{ url("/") }}';
                 var fullIconUrl = baseUrl + '/' + video.video_url;
                 // Change the background image to the full icon URL
                 $('#videoPreview source').attr('src',fullIconUrl);
                 // Load the video
                $('#videoPreview')[0].load();
                //  $('.custom-file-container__image-preview').css('background', 'url(' + fullIconUrl + ')');
                //  $('.custom-file-container__image-preview').css('background-repeat', 'no-repeat');
                //  $('.custom-file-container__image-preview').css('background-size', 'contain');
                //  $('.custom-file-container__image-preview').css('background-position', 'center');
             }
        });

        document.addEventListener('DOMContentLoaded', function () {
            // Get the file input and video element
            var fileInput = document.querySelector('.custom-file-container__custom-file__custom-file-input');
            var videoPreview = document.getElementById('videoPreview');

            // Listen for the change event on the file input
            fileInput.addEventListener('change', function () {
                // Check if a file is selected
                if (fileInput.files.length > 0) {
                    var file = fileInput.files[0];

                    // Create a URL for the selected file
                    var objectURL = URL.createObjectURL(file);

                    // Update the source of the video element
                    videoPreview.src = objectURL;
                }
            });

            // Get the clear button and listen for the click event
            var clearButton = document.querySelector('.custom-file-container__image-clear');
            clearButton.addEventListener('click', function () {
                // Clear the file input and reset the video element source
                fileInput.value = '';
                videoPreview.src = '#';
            });
        });

    </script>
@endpush

@section('content')

    <div id="content" class="main-content">
        <div class="layout-px-spacing">

            <div class="row layout-top-spacing">

                <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                    <div class="widget-content widget-content-area br-6">


                    <form action="{{ isset($video) ? route('admin.videos.update', $video->id) : route('admin.videos.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        @if(isset($video))
                            @method("PUT")
                        @endif

                        <div class="row">
                            <div class="form-group col-6">
                                <label for="exampleInputEmail1">Title</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter title" name="title" value="{{ old('title', isset($video) ? $video->title : '') }}" {{ isset($video) ? '' : 'required' }}>
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-6">
                                <label for="exampleInputEmail1">Series</label>
                                <select class="form-control basic" name="series_id">
                                    <option disabled selected value> -- Select Series-- </option>
                                    @foreach ($series as $option)
                                        <option value="{{ $option->id }}" {{ old('series_id', isset($video) ? ($video->series_id == $option->id ? 'selected' : '') : '') }}>{{ $option->title }}</option>
                                    @endforeach
                                </select>
                                @error('series_id')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group col-12">
                                <label for="description">Description</label>
                                <textarea class="form-control" name="description" id="description" cols="30" rows="10">{{ old('description', isset($video) ? $video->description : '') }}</textarea>
                                @error('description')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="custom-file-container col-12" data-upload-id="myVideo">
                                <label>Upload Video <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Video">x</a></label>
                                <label class="custom-file-container__custom-file">
                                    <input name="video_file" type="file" class="custom-file-container__custom-file__custom-file-input" accept="video/*" {{ isset($video) ? '' : 'required' }}>
                                    <input type="hidden" name="MAX_FILE_SIZE" value="104857600" />
                                    <span class="custom-file-container__custom-file__custom-file-control">Choose File</span>
                                </label>
                                <div class="custom-file-container__video-preview mt-3">
                                    <video id="videoPreview" controls width="100%" height="auto">
                                        <source src="#" type="video/mp4">
                                        Your browser does not support the video tag.
                                    </video>
                                </div>
                                @error('video_file')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group col-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>


                    </div>
                </div>

            </div>

        </div>

    </div>


@stop

resources/views/layouts/videos/icon.blade.php
<img src="{{ asset($category->icon) }}" height="50px" width="50px">

resources/views/layouts/videos/index.blade.php
@extends('master')
@push('end-style')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/table/datatable/datatables.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/table/datatable/custom_dt_html5.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/table/datatable/dt-global_style.css') }}">
@endpush
@push('end-script')
    <script src="{{ asset('assets/plugins/table/datatable/datatables.js') }}"></script>
    <!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/table/datatable/button-ext/buttons.print.min.js') }}"></script>
    <script>
        $('#videos_table').DataTable({
            "dom": "<'dt--top-section'<'row'<'col-sm-12 col-md-6 d-flex justify-content-md-start justify-content-center'B><'col-sm-12 col-md-6 d-flex justify-content-md-end justify-content-center mt-md-0 mt-3'f>>>" +
                "<'table-responsive'tr>" +
                "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
            buttons: {
                buttons: [{
                        extend: 'copy',
                        className: 'btn btn-sm'
                    },
                    {
                        extend: 'csv',
                        className: 'btn btn-sm'
                    },
                    {
                        extend: 'excel',
                        className: 'btn btn-sm'
                    },
                    {
                        extend: 'print',
                        className: 'btn btn-sm'
                    }
                ]
            },
            ajax: "{{ route('admin.videos.index') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'title',
                    name: 'title'
                },
                {
                    data: 'slug',
                    name: 'slug'
                },
                {
                    data: 'category',
                    name: 'category'
                },
                {
                    data: 'description',
                    name: 'description'
                },
                {
                    data: 'video',
                    name: 'video'
                },
                {
                    data: 'actions',
                    name: 'actions'
                }
            ],
            "oLanguage": {
                "oPaginate": {
                    "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>',
                    "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'
                },
                "sInfo": "Showing page _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Search...",
                "sLengthMenu": "Results :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [7, 10, 20, 50],
            "pageLength": 7
        });
    </script>
@endpush

@section('title')
    videos
@stop
@section('header')
    Video List
@stop

@section('content')

    <div id="content" class="main-content">
        <div class="layout-px-spacing">

            <div class="row layout-top-spacing">
                <div class="col-12">
                    <a type="button" href="{{route('admin.videos.create')}}" class="btn btn-dark float-right ms-auto mb-2">Add
                        Video</a>
                </div>

                <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                    <div class="widget-content widget-content-area br-6">

                        <table id="videos_table" class="table table-hover non-hover" style="width:100%">

                            <thead>

                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>slug </th>
                                    <th>category </th>
                                    <th>descreption</th>
                                    <th>video</th>
                                    <th class="dt-no-sorting">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <script>
        function DisableCategory(id) {
            swal.fire({
                title: "Are you sure to disable this category?",
                text: "User will not be able to see any products under this category",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, disable it!",
            }).then((result) => {
                //  console.log(isConfirm);
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: '{{ url('category_disable') }}/' + id,

                        success: function(data) {
                            $('#videos_table').DataTable().ajax.reload();
                            swal.fire("Success", " Category disabled successfully", "success");
                        },
                        error: function(error) {
                            Snackbar.show({
                                text: 'Somthing Went Wrong',
                                pos: 'top-right',
                                actionTextColor: '#fff',
                                backgroundColor: '#e7515a'
                            });
                        }
                    });
                }
            });

        }

        function ActiveCategory(id) {
            swal.fire({
                title: "Are you sure to Active this category?",
                text: "It will be visible to users",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Activate it!",
            }).then((result) => {
                //  console.log(isConfirm);
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: '{{ url('category_active') }}/' + id,

                        success: function(data) {
                            $('#videos_table').DataTable().ajax.reload();
                            swal.fire("Success", " Category Activated successfully", "success");
                        },
                        error: function(error) {
                            Snackbar.show({
                                text: 'Somthing Went Wrong',
                                pos: 'top-right',
                                actionTextColor: '#fff',
                                backgroundColor: '#e7515a'
                            });
                        }
                    });
                }
            });

        }

        function DeleteCategory(id) {
            swal.fire({
                title: "Are you sure to delete this category?",
                text: "All products under this category will automatically delete",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
            }).then((result) => {
                //  console.log(isConfirm);
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: '{{ url('category_delete') }}/' + id,

                        success: function(data) {
                            $('#videos_table').DataTable().ajax.reload();
                            swal.fire("Success", "Category deleted successfully", "success");
                        },
                        error: function(error) {
                            Snackbar.show({
                                text: 'Somthing Went Wrong',
                                pos: 'top-right',
                                actionTextColor: '#fff',
                                backgroundColor: '#e7515a'
                            });
                        }
                    });
                }
            });

        }
    </script>
@stop